spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: * # 替换成自己的用户名
    password: * # 替换成自己的密码
  data:
    redis:
      host: * # 替换成自己的 Redis地址
      port: 6379
      password: * # 替换成自己的 Redis密码
      database: 0  # 数据库索引（默认为0）
      client-name: lettuce
      lettuce:
        pool:
          max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
          min-idle: 1   # 连接池中的最小空闲连接
          max-idle: 30   # 连接池中的最大空闲连接
          max-wait: PT20S   # 最大阻塞等待时间（负数表示没有限制）,20s
      connect-timeout: 5000 # 连接超时时间
  servlet:
    multipart: # 设置文件上传规则
      max-file-size: 100MB  # 设置的单文件上传最大100M
      max-request-size: 1000MB  # 单个请求中文件总大小不超过1000M
  mail:
    host: smtp.qq.com   # 配置 smtp 服务器地址
    port: 587  # smtp 服务器的端口
    username: *  # 替换成自己的邮箱用户名(你的邮箱地址)
    password: *  # 替换成自己申请到的授权码
    default-encoding: UTF-8  # 配置邮件编码
    properties:
      mail:
        smtp:
          auth: true  # 开启验证
          starttls:
            required: true  # 是否必须通过使用加密通讯进行通讯
            enable: true    # 加密通讯
          socketFactoryClass: javax.net.ssl.SSLSocketFactory  # 配置 SSL 加密工厂

# 邮件发送方信息配置
email:
  from: * # 替换成自己的邮箱地址
  fromNickName: 往事随风的个人博客

# Swagger 配置
springdoc:
  api-docs:
    enabled: true # 启用或禁用API文档访问
    path: /v3/api-docs # API文档的路径
  swagger-ui:
    enabled: true # 启用或禁用Swagger UI访问
    path: /swagger-ui.html # Swagger UI的路径
    disable-swagger-default-url: true
    display-request-duration: true # 显示请求持续时间
  packages-to-scan:
    - com.nexus # 扫描的包路径

# token令牌
token:
  # 替换成自己设置的签名
  signature: *

# 文件上传
upload:
  prod: false
  base-path: * # 替换成自己文件在服务器上的保存路径
  base-url: http://127.0.0.1/ # 生成环境替换成自己的服务器地址或者域名

# 图片工具
image:
  # 水印
  water-mark-content: "@往事随風的个人博客：https://wk-blog.vip"

# 敏感词库
sensitive:
  word-path: * # 替换成自己敏感词库在服务器上的路径
  prod: false
  default-replace-str: "*"

# qq登录配置
qq:
  fmt: json
  client-id:
  redirect-uri:
  grant-type:
  client-secret:

# 和风天气
weather:
  key:
  geo-url:
  now-url: